# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x02pb\"Y\n\x0fSignUpUserInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x17\n\x0fpasswordConfirm\x18\x04 \x01(\t\"2\n\x0fGenericResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0fSignInUserInput\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"Q\n\x12SignInUserResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x15\n\rrefresh_token\x18\x03 \x01(\t\".\n\x12VerifyEmailRequest\x12\x18\n\x10verificationCode\x18\x01 \x01(\t2\xc2\x01\n\x0b\x41uthService\x12\x38\n\nSignUpUser\x12\x13.pb.SignUpUserInput\x1a\x13.pb.GenericResponse\"\x00\x12;\n\nSignInUser\x12\x13.pb.SignInUserInput\x1a\x16.pb.SignInUserResponse\"\x00\x12<\n\x0bVerifyEmail\x12\x16.pb.VerifyEmailRequest\x1a\x13.pb.GenericResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIGNUPUSERINPUT._serialized_start=18
  _SIGNUPUSERINPUT._serialized_end=107
  _GENERICRESPONSE._serialized_start=109
  _GENERICRESPONSE._serialized_end=159
  _SIGNINUSERINPUT._serialized_start=161
  _SIGNINUSERINPUT._serialized_end=211
  _SIGNINUSERRESPONSE._serialized_start=213
  _SIGNINUSERRESPONSE._serialized_end=294
  _VERIFYEMAILREQUEST._serialized_start=296
  _VERIFYEMAILREQUEST._serialized_end=342
  _AUTHSERVICE._serialized_start=345
  _AUTHSERVICE._serialized_end=539
# @@protoc_insertion_point(module_scope)
